__author__ = 'BryanC'


## TODO: LOAD THE DATA FILES

## TODO: ANALYSIS OF 'CONCURRENCY OF BUSINESSES' -- MIGHT NEED TO ACCOMODATE VARYING NAMES OF SAME BUSINESS

## BUSINESS TREND -- MAYBE GENRE/YEAR?



## TODO: CALL YELP API FOR CROSS REFERENCING BUSINESS TYPE TO NEIGHBOURHOOOD
## YELP HAS NEIGHBOURHOOD IN THE API CALL

